# This workflow runs e2e tests of master against LTS Kili app

name: E2E tests (master against LTS)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1-5" # once everyday at 13:00 UTC
jobs:
  recipes:
    name: Recipes test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: "pip"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install kili
        run: |
          pip install -e ".[dev]"

      - name: Set proper test server
        shell: bash
        run: |
          echo "TEST_AGAINST=LTS" >> $GITHUB_ENV
          echo "KILI_API_ENDPOINT=https://lts.cloud.kili-technology.com/api/label/v2/graphql" >> $GITHUB_ENV

      - name: Integration tests
        timeout-minutes: 10
        run: pytest -ra -sv --color yes --code-highlight yes --durations=15 -vv tests/e2e -k ".py"
        env:
          KILI_API_CLOUD_VISION: ${{ secrets.KILI_API_CLOUD_VISION }}
          KILI_API_ENDPOINT: ${{ env.KILI_API_ENDPOINT }}
          KILI_API_KEY: ${{ secrets[format('KILI_USER_API_KEY_{0}', env.TEST_AGAINST)] }}
          KILI_USER_EMAIL: ${{ secrets[format('KILI_USER_EMAIL_{0}', env.TEST_AGAINST)] }}
          KILI_USER_ID: ${{ secrets[format('KILI_USER_ID_{0}', env.TEST_AGAINST)] }}

      - name: Notebook tests
        timeout-minutes: 15
        run: pytest -ra -sv --color yes --code-highlight yes --durations=15 -vv tests/test_notebooks.py
        env:
          KILI_API_CLOUD_VISION: ${{ secrets.KILI_API_CLOUD_VISION }}
          KILI_API_ENDPOINT: ${{ env.KILI_API_ENDPOINT }}
          KILI_API_KEY: ${{ secrets[format('KILI_USER_API_KEY_{0}', env.TEST_AGAINST)] }}
          KILI_USER_EMAIL: ${{ secrets[format('KILI_USER_EMAIL_{0}', env.TEST_AGAINST)] }}
          KILI_USER_ID: ${{ secrets[format('KILI_USER_ID_{0}', env.TEST_AGAINST)] }}

      - name: Slack notification if failure
        if: failure() && (github.event_name != 'workflow_dispatch') # doesn't notify for manual runs
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "E2E tests (master against LTS) failed: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "E2E tests (master against LTS) failed: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PYTHON_SDK_ALARMING }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
