name: pyright

on: [push]

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.10', '3.7']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run pyright
        run: pyright .
