name: Create draft release minor
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Enter the release branch version release/X.XXX.0 (use 'Create release branch' workflow beforehand to create the branch)"
        required: true
        type: string
        default: "X.XXX.0"

jobs:
  create_draft_release:
    runs-on: ubuntu-latest
    name: create draft release

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      - name: Install kili
        run: pip install -e .

      - name: Set git identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: checkout to release branch
        run: |
          git fetch origin release/${{ inputs.releaseVersion }}
          git checkout release/${{ inputs.releaseVersion }}
          git status

      - name: create draft release
        run: |
          link_to_draft=$(./entrypoint.sh release:draft ${{ inputs.releaseVersion }})
          echo $link_to_draft
          echo "LINK_TO_DRAFT=$link_to_draft" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}
